# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt beep extendedglob nomatch notify
unsetopt autocd
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/austin/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# autogenerated by wasmtime installation
export WASMTIME_HOME="$HOME/.wasmtime"

export PATH="$WASMTIME_HOME/bin:$PATH"

# CONFIG BY ME #####################################################################################
# [s]tart
alias s='source ~/.my-scripts/tmux-start.sh'
# [sp]lit
alias sp='source ~/.my-scripts/tmux-split.sh'
# [c]lose
alias c='source ~/.my-scripts/tmux-close.sh'

# ENVIRONMENT-SPECIFIC CONFIGURATIONS ##############################################################
# mac 
if [ -f ".zshrc-mac" ]; then
    source ~/.zshrc-mac
fi

# linux
if [ -f ".zshrc-linux" ]; then
    source ~/.zshrc-linux
fi

# work
if [ -f ".zshrc-work" ]; then
    source ~/.zshrc-work
fi

# use neovim by default when editing files in git
export GIT_EDITOR=nvim

# make sure tmux has correct config
tmux source ~/.config/tmux/tmux.conf

# ZSH PLUGINS #######################################################################################
# git - comes with zsh
plugin=(git)

# CUSTOMIZING COMMAND LINE PROMPT ###################################################################
# see https://arjanvandergaag.nl/blog/customize-zsh-prompt-with-vcs-info.html
# creates color formatting string based on current staged status
parse_git_dirty() {
  git_status="$(git status 2> /dev/null)"
  [[ "$git_status" =~ "Changes to be committed:" ]] && echo -n "%F{green}"
  [[ "$git_status" =~ "Changes not staged for commit:" ]] && echo -n "%F{yellow}"
  [[ "$git_status" =~ "Untracked files:" ]] && echo -n "%F{red}"
}

# zsh-specific config stuff
# substite of parameters inside the prompt each time the prompt is drawn.
setopt prompt_subst
autoload -Uz vcs_info # enable vcs_info
precmd () { vcs_info } # always load before displaying the prompt
zstyle ':vcs_info:git*' formats ' %b' # format $vcs_info_msg_0_
PS1='%F{254}%n%F{245} %F{153}%(5~|%-1~/⋯/%3~|%4~)%f$(parse_git_dirty)${vcs_info_msg_0_} %F{254}λ%f '

# SETUP ZOXIDE ####################################################################################
eval "$(zoxide init zsh)"

