# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt beep extendedglob nomatch notify
unsetopt autocd
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/austin/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# autogenerated by wasmtime installation
export WASMTIME_HOME="$HOME/.wasmtime"

export PATH="$WASMTIME_HOME/bin:$PATH"

# CONFIG BY ME ##############################################################################################
# [s]tart - Start or attach to a tmux session
# Examples:
#   s              # Start/attach default session named 'zsh'
#   s myproject    # Start/attach session named 'myproject' with splits
alias s='source ~/.my-scripts/tmux-start.sh'

# [se]tup - Setup multi-window tmux session for code projects
# Creates windows for multiple work directories (Notability projects, staging, reviews)
# Examples:
#   se             # Create/attach 'code' session with predefined windows
#   se mywork      # Create/attach 'mywork' session with predefined windows
alias se='source ~/.my-scripts/tmux-setup.sh'

# [sp]lit - Create tmux pane layouts
# Examples:
#   sp terms       # Create vertical terminals (default: 4 panes)
#   sp |           # Editor on left with terminals on right
#   sp -           # Main area above with 2 panes below
#   sp terms 3     # Create 3 vertical terminals
#   sp - 2 3       # Main above with 2 vertical splits and 3 horizontal splits below
alias sp='source ~/.my-scripts/tmux-split.sh'

# [c]lose - Close all tmux panes except the current one
# Example:
#   c              # Closes all other panes in current session
alias c='source ~/.my-scripts/tmux-close.sh'

# GIT ALIASES ###############################################################################################
# This allows not having to store the actual root .gitconfig in git itself, which quickly becomes problematic
if ! git config --global --get "alias.co" >/dev/null; then
    git config --global alias.co checkout
fi

if ! git config --global --get "alias.br" >/dev/null; then
    git config --global alias.br branch
fi

if ! git config --global --get "alias.cm" >/dev/null; then
    git config --global alias.cm commit
fi

if ! git config --global --get "alias.st" >/dev/null; then
    git config --global alias.st status
fi

if ! git config --global --get "alias.p" >/dev/null; then
    git config --global alias.p push
fi

if ! git config --global --get "alias.pl" >/dev/null; then
    git config --global alias.pl pull
fi

if ! git config --global --get "alias.lg" >/dev/null; then
    git config --global alias.lg 'log --oneline'
fi

# Rewrite commits with different email
#
# Examples:
# To change the author name:
# git change-commits GIT_AUTHOR_NAME "old name" "new name"
#
# or the email for only the last 10 commits:
# git change-commits GIT_AUTHOR_EMAIL "old@email.com" "new@email.com" HEAD~10..HEAD
#
# See https://stackoverflow.com/questions/2919878/git-rewrite-previous-commit-usernames-and-emails
if ! git config --global --get "alias.change-commits" >/dev/null; then
    git config --global alias.change-commits '!'"f() { VAR=\$1; OLD=\$2; NEW=\$3; shift 3; git filter-branch --env-filter \"if [[ \\\"\$\`echo \$VAR\`\\\" = '\$OLD' ]]; then export \$VAR='\$NEW'; fi\" \$@; }; f"
fi


# Search for PRs via CLI
#
# From Dan Susman
if ! git config --global --get "alias.pr" >/dev/null; then
    git config --global alias.pr "!gh pr ls -L 100 | fzf | sed -E \"s/^([0-9]+).*/\\1/\" | xargs gh pr checkout"
fi

if ! git config --global --get "core.editor" >/dev/null; then
    git config --global core.editor nvim
fi

if ! git config --global --get "core.excludeFile" >/dev/null; then
    git config --global core.excludeFile ~/.gitignore
fi


# ENVIRONMENT-SPECIFIC CONFIGURATIONS #######################################################################
# mac 
if [ -f ~/.zshrc-mac ]; then
    source ~/.zshrc-mac
fi

# linux
if [ -f ~/.zshrc-linux ]; then
    source ~/.zshrc-linux
fi

# work
if [ -f ~/.zshrc-work ]; then
    source ~/.zshrc-work
fi

# use neovim by default when editing files in git
export GIT_EDITOR=nvim

# make sure tmux has correct config
tmux source ~/.config/tmux/tmux.conf

# ZSH PLUGINS ################################################################################################
# git - comes with zsh
plugin=(git)

# CUSTOMIZING COMMAND LINE PROMPT ############################################################################
# see https://arjanvandergaag.nl/blog/customize-zsh-prompt-with-vcs-info.html
# creates color formatting string based on current staged status
parse_git_dirty() {
  git_status="$(git status 2> /dev/null)"
  [[ "$git_status" =~ "Changes to be committed:" ]] && echo -n "%F{green}"
  [[ "$git_status" =~ "Changes not staged for commit:" ]] && echo -n "%F{yellow}"
  [[ "$git_status" =~ "Untracked files:" ]] && echo -n "%F{red}"
}

# zsh-specific config stuff
# substite of parameters inside the prompt each time the prompt is drawn.
setopt prompt_subst
autoload -Uz vcs_info # enable vcs_info
precmd () { vcs_info } # always load before displaying the prompt
zstyle ':vcs_info:git*' formats ' %b' # format $vcs_info_msg_0_
PS1='%F{254}%n%F{245} %F{153}%(5~|%-1~/⋯/%3~|%4~)%f$(parse_git_dirty)${vcs_info_msg_0_} %F{254}λ%f '

# SETUP ZOXIDE #############################################################################################
eval "$(zoxide init zsh)"

# SETUP PYENV ##############################################################################################
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"


