[package]
name = "config-cli"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
config-manifest = { path = "../config-manifest" }
deps-core = { path = "../deps-core" }
dotfiles-path = { path = "../dotfiles-path" }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
