//! `config help`: list the config subcommands and what each one does.
//!
//! Ported from `.scripts/config/config-help`, which stays as a shim so the
//! dispatcher still resolves the verb: `.scripts/config/config` finds a verb
//! only by testing `[ -x "$here/config-<verb>" ]` and otherwise falls through
//! to git, with no `config-cli` fallback, so deleting the file would turn
//! `config help` into `git help` permanently.
//!
//! The listing is generated by asking each `config-<sub>` beside the shim to
//! describe itself, so a new utility documents itself the moment it lands
//! there. A hand-written list would be a second copy of the same facts, and
//! the one that nobody edits is the one that goes stale.
//!
//! Asked rather than read: the description used to come from a
//! `sed -n 's/^# help: //p'` over the subcommand's source text, which assumed
//! every subcommand is a readable text file. Against a compiled binary that
//! sed prints "RE error: illegal byte sequence" to stderr and the pipeline
//! still exits 0, so the listing lost the description and gained an error
//! line without failing.

use std::path::PathBuf;
use std::process::{Command, ExitCode};

/// The environment variable that names the directory to enumerate.
///
/// A seam, not a knob. The shim exports it so a copy of the shim run out of a
/// fixture directory lists that directory's siblings, which is how
/// `tests/config-usage.test.sh` exercises the odd-shaped ones without leaving
/// a stray `config-*` in the real `.scripts/config` that every other suite
/// counts. Unset, the listing reads the real directory.
const SUBCOMMAND_DIR_VAR: &str = "CONFIG_SUBCOMMAND_DIR";

/// The column width each subcommand name is padded to.
///
/// Matches the shell version's `printf '  %-14s %s\n'`. The width is part of
/// the recorded output that `tests/fixtures/config-help-before-describe.txt`
/// pins, so it is a contract rather than a formatting preference.
const NAME_COLUMN_WIDTH: usize = 14;

/// The text a subcommand's row carries when it cannot be asked.
const UNDOCUMENTED: &str = "(undocumented)";

/// `config help`'s arguments: the two flags every subcommand answers, and
/// nothing else.
///
/// The listing itself takes no options. `config help --help` and
/// `config --help` both print the shim's usage block and then this listing,
/// because the listing is what help is for. For the flags a single subcommand
/// takes, ask that subcommand: `config test --help`.
#[derive(clap::Args)]
// `override_usage` rather than the derived line: clap renders subcommand
// usage as `<parent bin_name> <subcommand>`, which would print
// `config-cli help`. The dispatcher's own name is `config`, and the shim's
// `# usage:` block says `config help`, so the two must agree.
//
// `disable_help_flag` because `help` is the one subcommand that must not stop
// at `--help`. Clap's auto-generated flag prints its own help and exits, which
// would hide the listing from `config --help`, and its name also collides with
// the `help` field declared below.
#[command(override_usage = "config help", disable_help_flag = true)]
pub(crate) struct HelpArgs {
    /// Accepted so the flag every subcommand answers is not a parse error
    /// here, and otherwise ignored.
    ///
    /// The shim answers `--describe` itself, out of its own `# help:` line,
    /// and never reaches the binary with it. A second copy of that string
    /// here would be the copy that drifts, which is the same reason the
    /// listing asks its siblings instead of embedding them.
    #[arg(long)]
    describe: bool,

    /// Print the listing, having been asked for help.
    ///
    /// Accepted and ignored. The shim prints the usage block itself and then
    /// forwards the rest, because `help` is the one subcommand that does not
    /// stop at `--help`: printing the block and exiting would hide the
    /// listing from `config --help`, which the dispatcher routes here and
    /// which readers expect to answer "what commands exist". The flag is
    /// still declared so invoking the binary directly with it prints the
    /// listing rather than a parse error.
    #[arg(long, short = 'h')]
    help: bool,
}

/// One row of the listing: a subcommand's name and what it says it does.
struct Row {
    name: String,
    description: String,
}

/// Run `config help`.
///
/// Always exits successfully. A sibling that cannot be asked is reported in
/// its own row as `(undocumented)` rather than failing the listing, matching
/// the shell version: a listing that refuses to print because one entry is
/// odd is less useful than one that names the odd entry.
pub(crate) fn run(arguments: HelpArgs) -> ExitCode {
    // Neither flag is branched on: with or without them the answer this
    // binary gives is the listing, because the shim has already handled the
    // cases where the answer is anything else. See each field's own
    // documentation.
    let _ = (arguments.describe, arguments.help);

    print_listing(&subcommand_dir());
    ExitCode::SUCCESS
}

/// The directory whose `config-*` entries the listing enumerates.
///
/// `CONFIG_SUBCOMMAND_DIR` when the shim exported it, so a shim run out of a
/// copied directory lists that copy's siblings. Otherwise `~/.scripts/config`,
/// which is where the dispatcher and its subcommands live.
fn subcommand_dir() -> PathBuf {
    // An empty value is treated as unset, so a caller that exports the
    // variable without a value gets the real directory rather than an empty
    // listing from enumerating "".
    if let Some(directory) = std::env::var_os(SUBCOMMAND_DIR_VAR)
        && !directory.is_empty()
    {
        return PathBuf::from(directory);
    }
    match std::env::var_os("HOME") {
        Some(home) => PathBuf::from(home).join(".scripts/config"),
        // An unset $HOME leaves nothing to resolve the default against. The
        // relative path still enumerates something when the caller happens to
        // be standing in the repo, and enumerating nothing is the honest
        // result otherwise, which the empty listing shows.
        None => PathBuf::from(".scripts/config"),
    }
}

/// Print the header, one row per sibling, and the trailing notes.
///
/// The exact text is pinned by
/// `tests/fixtures/config-help-before-describe.txt`, which was captured
/// before any `--describe` work existed, so a match proves the port is
/// invisible in the output rather than merely self-consistent.
fn print_listing(directory: &std::path::Path) {
    println!("usage: config <command> [args]");
    println!("       config <git-command> [args]");
    println!();
    println!("Commands:");

    for row in rows(directory) {
        println!(
            "  {:<width$} {}",
            row.name,
            row.description,
            width = NAME_COLUMN_WIDTH
        );
    }

    println!();
    println!("Run `config <command> --help` for the flags a command takes.");
    println!();
    println!("Any other verb is passed to git on the bare repo at ~/.cfg, so every");
    println!("git command works: config status, config add <path>, config commit.");
}

/// Collect one row per `config-*` sibling, sorted by name.
///
/// Sorted explicitly because the shell version enumerated through a glob,
/// which the shell expands in sorted order, while `read_dir` yields whatever
/// order the filesystem hands back. The ordering is part of the pinned
/// output.
fn rows(directory: &std::path::Path) -> Vec<Row> {
    let Ok(entries) = std::fs::read_dir(directory) else {
        return Vec::new();
    };

    let mut rows: Vec<Row> = entries
        .filter_map(|entry| entry.ok())
        .filter_map(|entry| {
            let path = entry.path();
            // Directories are skipped for the same reason the shell version's
            // `[ -f "$script" ]` skipped them: the dispatcher execs a file.
            if !path.is_file() {
                return None;
            }
            let name = path.file_name()?.to_str()?.strip_prefix("config-")?;
            Some(Row {
                name: name.to_owned(),
                description: describe_sibling(&path),
            })
        })
        .collect();

    rows.sort_by(|left, right| left.name.cmp(&right.name));
    rows
}

/// Ask one sibling what it does, degrading to `(undocumented)`.
///
/// Only an executable sibling is reachable through the dispatcher, which
/// requires `-x` before it execs. A file the listing names but the dispatcher
/// will not run has no description to ask for, and asking anyway would put a
/// permission error in the column where the description belongs.
///
/// Only the first line is taken, and stderr is discarded, because the column
/// is one line wide and a sibling's diagnostics are not its description.
fn describe_sibling(path: &std::path::Path) -> String {
    if !is_executable(path) {
        return UNDOCUMENTED.to_owned();
    }

    let output = Command::new(path)
        .arg("--describe")
        .stderr(std::process::Stdio::null())
        .output();

    let Ok(output) = output else {
        return UNDOCUMENTED.to_owned();
    };

    let stdout = String::from_utf8_lossy(&output.stdout);
    match stdout.lines().next() {
        Some(line) if !line.is_empty() => line.to_owned(),
        _ => UNDOCUMENTED.to_owned(),
    }
}

/// Whether the file carries any execute bit.
///
/// Any bit rather than the caller's own, matching the dispatcher's `-x` test
/// closely enough for the only distinction that matters here: a file with no
/// execute bit at all is one the dispatcher will never run.
fn is_executable(path: &std::path::Path) -> bool {
    use std::os::unix::fs::PermissionsExt;
    match std::fs::metadata(path) {
        Ok(metadata) => metadata.permissions().mode() & 0o111 != 0,
        Err(_) => false,
    }
}
