# Notes to self:
# General hotkey principles:
# - all shortcuts for windows things begin with `alt-shift` modifiers
# - use `ctrl` modifier for moving things
# - use plain `alt` for viewing things

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 4
    inner.vertical =   4
    outer.left =       4
    outer.bottom =     4
    outer.top =        4
    outer.right =      4

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]
    # All possible modifiers: cmd, alt, ctrl, shift
    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    alt-shift-slash = 'layout tiles horizontal vertical'

    # Moving focus/windows between nodes
    ####################################################################
    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    # Move focus between windows
    alt-shift-h = 'focus left'
    alt-shift-j = 'focus down'
    alt-shift-k = 'focus up'
    alt-shift-l = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    # Move windows between nodes
    ctrl-alt-shift-h = 'move left'
    ctrl-alt-shift-j = 'move down'
    ctrl-alt-shift-k = 'move up'
    ctrl-alt-shift-l = 'move right'

    # Moving focus/nodes between workspaces
    ####################################################################
    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    alt-shift-q = 'workspace q'
    alt-shift-w = 'workspace w'
    alt-shift-f = 'workspace f'
    alt-shift-p = 'workspace p'
    alt-shift-b = 'workspace b'
    #
    alt-shift-a = 'workspace a'
    alt-shift-r = 'workspace r'
    alt-shift-s = 'workspace s'
    alt-shift-t = 'workspace t'
    alt-shift-g = 'workspace g'
    #
    alt-shift-z = 'workspace z'
    alt-shift-x = 'workspace x'
    alt-shift-c = 'workspace c'
    alt-shift-d = 'workspace d'
    alt-shift-v = 'workspace v'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    ctrl-alt-shift-q = 'move-node-to-workspace q'
    ctrl-alt-shift-w = 'move-node-to-workspace w'
    ctrl-alt-shift-f = 'move-node-to-workspace f'
    ctrl-alt-shift-p = 'move-node-to-workspace p'
    ctrl-alt-shift-b = 'move-node-to-workspace b'
    # 
    ctrl-alt-shift-a = 'move-node-to-workspace a'
    ctrl-alt-shift-r = 'move-node-to-workspace r'
    ctrl-alt-shift-s = 'move-node-to-workspace s'
    ctrl-alt-shift-t = 'move-node-to-workspace t'
    ctrl-alt-shift-g = 'move-node-to-workspace g'
    # 
    ctrl-alt-shift-z = 'move-node-to-workspace z'
    ctrl-alt-shift-x = 'move-node-to-workspace x'
    ctrl-alt-shift-c = 'move-node-to-workspace c'
    ctrl-alt-shift-d = 'move-node-to-workspace d'
    ctrl-alt-shift-v = 'move-node-to-workspace v'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    ctrl-alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # Swiching modes
    ####################################################################
    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    # reload config
    esc = ['reload-config', 'mode main']
    # reset layout
    r = ['flatten-workspace-tree', 'mode main'] 
    # toggle between floating and tiling layout
    f = ['layout floating tiling', 'mode main'] 

    ctrl-alt-shift-h = ['join-with left', 'mode main']
    ctrl-alt-shift-j = ['join-with down', 'mode main']
    ctrl-alt-shift-k = ['join-with up', 'mode main']
    ctrl-alt-shift-l = ['join-with right', 'mode main']

