[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
key = "N"
mods = "Command"

[keyboard.bindings.command]
args = ["-n", "/Applications/Alacritty.app"]
program = "open"

[window]
option_as_alt = "Both"
startup_mode = "Maximized"
