#!/bin/sh
# Regenerates ~/.config/alacritty/alacritty-platform.toml, the single import
# the shared alacritty.toml reaches for.
#
# Alacritty has no conditional import: a shared config that imported both
# alacritty-mac.toml and alacritty-linux.toml would apply both on every
# machine. So the shared config imports one stable, platform-neutral path and
# this script points that path at the right variant.
#
# The generated file is the only per-machine artifact in the Alacritty config
# and is deliberately untracked. Both real variants stay tracked and stay
# inside `config check`.
#
# Run by shell startup and by `config reload`, so it must be cheap,
# idempotent, and safe to run when nothing has changed.
set -eu

. "$(dirname "$(readlink -f "$0")")/platform.sh"

ALACRITTY_DIR=${ALACRITTY_DIR:-"$HOME/.config/alacritty"}
pointer="$ALACRITTY_DIR/alacritty-platform.toml"
variant=$(platform_variant "$ALACRITTY_DIR/alacritty.toml")

# An unknown platform gets an empty pointer rather than a guess. Alacritty
# then runs on the shared config alone, which is a working terminal.
if [ ! -f "$variant" ]; then
    variant=''
fi

# Copied rather than symlinked: a symlink into the repo breaks if the home
# directory is synced to a machine where the target does not exist, and
# Alacritty follows it silently either way. A copy always reads as itself.
new="# GENERATED by ~/.scripts/alacritty-platform.sh -- do not edit, and do
# not track. Rewritten from alacritty-${DOTFILES_PLATFORM}.toml on every shell
# startup and every \`config reload\`.
"
if [ -n "$variant" ]; then
    new="$new$(cat "$variant")"
fi

# Written only when the content actually differs. This runs at every shell
# startup, and 107 tmux panes rewriting the same file would be 107 writes
# Alacritty may be watching.
if [ -f "$pointer" ] && [ "$(cat "$pointer")" = "$new" ]; then
    exit 0
fi

mkdir -p "$ALACRITTY_DIR"
printf '%s' "$new" > "$pointer"
