#!/bin/sh
# Regenerates ~/.config/alacritty/alacritty-platform.toml, the single import
# the shared alacritty.toml reaches for.
#
# Alacritty has no conditional import: a shared config that imported both
# alacritty-mac.toml and alacritty-linux.toml would apply both on every
# machine. So the shared config imports one stable, platform-neutral path and
# this script points that path at the right variant.
#
# The generated file is the only per-machine artifact in the Alacritty config
# and is deliberately untracked. Both real variants stay tracked, so a machine
# that switches platform needs no new files.
#
# Run by shell startup and by `config reload`, so it must be cheap,
# idempotent, and safe to run when nothing has changed.
set -eu

. "$(dirname "$(readlink -f "$0")")/platform.sh"

ALACRITTY_DIR=${ALACRITTY_DIR:-"$HOME/.config/alacritty"}
pointer="$ALACRITTY_DIR/alacritty-platform.toml"
variant=$(platform_variant "$ALACRITTY_DIR/alacritty.toml")

# An unknown platform gets an empty pointer rather than a guess. Alacritty
# then runs on the shared config alone, which is a working terminal.
if [ ! -f "$variant" ]; then
    variant=''
fi

# Copied rather than symlinked: a symlink into the repo breaks if the home
# directory is synced to a machine where the target does not exist, and
# Alacritty follows it silently either way. A copy always reads as itself.
new="# GENERATED by ~/.scripts/alacritty-platform.sh -- do not edit, and do
# not track. Rewritten from alacritty-${DOTFILES_PLATFORM}.toml on every shell
# startup and every \`config reload\`.
"
if [ -n "$variant" ]; then
    new="$new$(cat "$variant")"
fi

# Written only when the content actually differs. This runs at every shell
# startup, and 107 tmux panes rewriting the same file would be 107 writes
# Alacritty may be watching.
if [ -f "$pointer" ] && [ "$(cat "$pointer")" = "$new" ]; then
    exit 0
fi

mkdir -p "$ALACRITTY_DIR"

# Written to a temp file and renamed, not truncated in place. `.zshrc:188`
# backgrounds this script from every shell, so on the first startup after a
# variant edit every pane runs it at once and the content guard above lets
# them all through. `printf > "$pointer"` truncates first and fills after, and
# Alacritty is watching the file: a read landing in that window gets a partial
# config, and Alacritty applies what it managed to parse.
#
# Measured with a sampling reader against a 208KB payload, one writer looping:
#
#   printf > pointer      1,863 zero-length and 467,087 partial reads
#                         out of 3.27M, so 14% of reads saw a broken file
#   mktemp + mv -f        0 zero-length and 0 partial out of 3.49M
#
# rename(2) is atomic within a filesystem, so a reader sees either the old
# file or the new one. The temp file is created in $ALACRITTY_DIR rather than
# $TMPDIR to keep both paths on one filesystem; a cross-device mv falls back
# to copy-then-rename and reintroduces the window it exists to close.
tmp=$(mktemp "$ALACRITTY_DIR/.alacritty-platform.toml.XXXXXX") || exit 1
trap 'rm -f "$tmp"' EXIT INT TERM
printf '%s' "$new" > "$tmp"
mv -f "$tmp" "$pointer"
trap - EXIT INT TERM
